version: '3.8'

services:
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        container_name: node_app-luanvan
        restart: always
        ports:
            - '3001:3001'
        environment:
            - PORT=3001
            - DB_HOST=mysql-luanvan
            - DB_PORT=3306
            # - DB_HOST=host.docker.internal
            - MINIO_ENDPOINT=minio
            # - MINIO_ENDPOINT=host.docker.internal
            - MINIO_PORT=9000
            - MINIO_ROOT_USER=minio090202
            - MINIO_ROOT_PASSWORD=minio090202
            # - URL_REACT=http://localhost
        expose:
            - 3001
        depends_on:
            - mysql-luanvan
            - minio
        volumes:
            - ../:/app
            - /app/node_modules
        working_dir: /app
        command: npm run dev

    mysql-luanvan:
        image: mysql:8.0
        container_name: mysql-luanvan
        restart: always
        ports:
            - '3307:3306'
        environment:
            - MYSQL_DATABASE=luanvancntt
            - MYSQL_ROOT_PASSWORD=090202
        expose:
            - '3306'
        volumes:
            - mysql_data:/data/db

    minio:
        image: minio/minio
        container_name: minio-luanvan
        restart: always
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minio090202
            - MINIO_ROOT_PASSWORD=minio090202
        volumes:
            - minio_data:/data
        command: server --console-address ":9001" /data

    nginx:
        image: nginx:latest
        container_name: nginx-luanvan
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - minio
        networks:
            - default

volumes:
    mysql_data:
    minio_data:
# docker compose -p luanvan_backend up --build -d
