version: '3.8'
services:
    db-luanvan:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=luanvancntt
            - MYSQL_ROOT_PASSWORD=090202
        ports:
            - '3307:3306'

    minio:
        image: minio/minio
        restart: always
        environment:
            - MINIO_ROOT_USER=minio090202
            - MINIO_ROOT_PASSWORD=minio090202
        ports:
            - '9000:9000'
            - '9001:9001'
        command: server --console-address ":9001" /data
        volumes:
            - ./data:/data
